[tracing.filters]
default = "debug"
tantivy = "warn"

[http]
# address = "0.0.0.0"
port = 8080

[schema]
default = "saint-coinach"

[schema.saint_coinach]
# remote = "https://github.com/xivapi/SaintCoinach.git"
directory = "saint_coinach"

[search.index]
directory = "search"

[search.ingest]
concurrency = 10
memory = 52428800 # 50MiB
