[tracing.filters]
default = "debug"
tantivy = "warn"
hyper = "info"

[http]
# address = "0.0.0.0"
port = 8080

[data]
language = "en"

[data.patch]
directory = "patches"
concurrency = 4

[version]
interval = 3600 # 1 hour
directory = "versions"
repositories = [
  "4e9a232b", # ffxiv
  "6b936f08", # ex1 (hw)
  "f29a3eb2", # ex2 (stb)
  "859d0e24", # ex3 (shb)
  "1bf99b87", # ex4 (ew)
]

[version.thaliak]
endpoint = "https://thaliak.xiv.dev/graphql/2022-08-14"

[schema]
default = "saint-coinach"

[schema.saint_coinach]
# remote = "https://github.com/xivapi/SaintCoinach.git"
directory = "saint_coinach"

[search2.tantivy]
directory = "search2"
memory = 52428800 # 50MiB
