[package]
name = "boilmaster"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.55"
axum = "0.5.3"
axum-macros = "0.2.0"
ironworks = {path = "../ironworks", features = ["ffxiv", "sqpack"]}
thiserror = "1.0.30"
tokio = { version = "1.17.0", features = ["full"] }
