[package]
name = "boilmaster"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.55"
axum = "0.5.3"
axum-macros = "0.2.0"
either = "1.8.0"
figment = {version = "0.10.8", features = ["env", "toml"]}
futures = "0.3.25"
ironworks = {path = "../ironworks", features = ["excel", "sqpack"]}
ironworks_schema = {path = "../schema", features = ["saint_coinach"]}
nom = "7.1.1"
serde = {version = "1.0.137", features = ["derive"]}
tantivy = "0.19.0"
thiserror = "1.0.30"
tokio = {version = "1.17.0", features = ["full"]}
tokio-util = "0.7.4"
tower-http = {version = "0.3.0", features = ["trace"]}
tracing = "0.1.34"
tracing-subscriber = "0.3.11"
