[package]
name = "boilmaster"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.55"
axum = "0.5.3"
axum-macros = "0.2.0"
ironworks = {path = "../ironworks", features = ["excel", "ffxiv", "sqpack"]}
thiserror = "1.0.30"
tokio = {version = "1.17.0", features = ["full"]}
tower-http = {version = "0.3.0", features = ["trace"]}
tracing = "0.1.34"
tracing-subscriber = "0.3.11"
