[package]
name = "temp_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.55"
ironworks_excel = {path = "../ironworks_excel"}
ironworks_ffxiv = {path = "../ironworks_ffxiv"}
ironworks_sqpack = {path = "../ironworks_sqpack"}