[package]
name = "ironworks_sqpack"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binrw = "0.8.4"
flate2 = "1.0.22"
glob = "0.3.0"
thiserror = "1.0.30"
