[package]
name = "nero"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.7"
bevy_egui = "0.14"

# TODO: target gate to wasm
wasm-bindgen = "0.2.80"
web-sys = { version = "0.3.57", features = [
  "Document",
  "Element",
  "Event",
  "EventTarget",
  "File",
  "FileList",
  "HtmlElement",
  "HtmlInputElement",
  "Window",
] }