[package]
name = "ironworks"
version = "0.1.0"
edition = "2021"

[features]
sqpack = []

[dependencies]
# TODO: Which of these should be optional?
binrw = "0.8.4"
flate2 = "1.0.22"
thiserror = "1.0.30"