[package]
name = "ironworks"
version = "0.1.0"
authors = ["ackwell <saxon@ackwell.com.au>"]
edition = "2021"
description = "Modular FFXIV data toolkit written in rust."
readme = "../README.md"
repository = "https://github.com/ackwell/ironworks"
license = "MIT"

[features]
excel = ["enum-as-inner", "num_enum"]
ffxiv = []
sqpack = ["flate2"]

[dependencies]
binrw = "0.8.4"
thiserror = "1.0.30"

enum-as-inner = {version = "0.4.0", optional = true}
flate2 = {version = "1.0.22", optional = true}
num_enum = {version = "0.5.7", optional = true}
