[package]
name = "ironworks"
version = "0.1.0"
edition = "2021"

[features]
excel = ["num_enum"]
sqpack = ["flate2"]

[dependencies]
binrw = "0.8.4"
thiserror = "1.0.30"

flate2 = {version = "1.0.22", optional = true}
num_enum = {version = "0.5.7", optional = true}
